experiment_name: GNN_NCM_Tuned_Run
seed: 42
device: cuda
data:
  data_dir: data/processed
  target_nodes:
  - VOL
  - LIQ
model:
  name: GNN_NCM
  gnn_mode: per_edge
  hidden_dim: 16
  out_dim: 8
  noise_dim: 4
training:
  type: HybridCausalTrainer
  epochs: 200
  lr: 0.01
  gamma: 0.2
  batch_size: 64
output:
  output_dir: outputs
