# --- Experiment Settings ---
experiment_name: "GNN_NCM_Base_Run"
seed: 42
device: "cuda" # 'cuda' or 'cpu'


# --- Model Hyperparameters ---
model:
  name: "GNN_NCM"
  gnn_mode: "per_edge" # 'per_edge' or 'shared'
  hidden_dim: 32
  out_dim: 16
  noise_dim: 4

# --- Training Settings ---
training:
  type: "HybridCausalTrainer"
  epochs: 50
  lr: 0.005
  gamma: 0.5 # Weight for the causal regularizer

# --- Output Settings ---
output_dir: "outputs"