experiment_name: GNN_NCM_TwoPart_VOL
seed: 42
device: cuda
data:
  target_node: VOL
  batch_size: 1
model:
  name: GNN_NCM
  gnn_mode: per_edge
  hidden_dim: 64
  out_dim: 16
  noise_dim: 4
training:
  type: CausalTwoPartTrainer
  epochs_obs: 20
  epochs_do: 30
  lr: 0.0001
  weight_decay: 0.0001
  clip: 0.5
  w_obs: 0.5
  w_do: 2
  neutral: zeros
  delta: 0.1
output:
  output_dir: outputs

