# configs/two_part_vol.yaml
experiment_name: GNN_NCM_TwoPart_VOL
seed: 42
device: cuda

data:
  data_dir: data/processed
  target_node: VOL      # singular, VOL-only
  batch_size: 1         # graphs are per-day; keep 1 for stability

model:
  name: GNN_NCM
  gnn_mode: per_edge
  hidden_dim: 16
  out_dim: 8
  noise_dim: 4

training:
  type: CausalTwoPartTrainer
  epochs_obs: 30
  epochs_do: 10
  lr: 0.01
  weight_decay: 1e-4
  clip: 1.0
  w_obs: 0.2
  w_do: 1.0
  neutral: zeros        # or "self+delta"
  delta: 0.1            # used only if neutral == "self+delta"

output:
  output_dir: outputs
